spring:
  application:
    name: cue
  datasource:
    url: jdbc:postgresql://localhost:5432/cue_db
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
logging:
    level:
      org:
        hibernate:
          SQL: INFO
          orm:
            jdbc:
              bind: INFO
security:
  jwt:
    secret-key: 232b2c9536bd685d1b84da22853bd9592375c1d8b9d791ec22ae3971019828ea